### ISSUE TITLE
client-influx.py: do not use bool

### ISSUE THREAD

**Issue by lemoer** [mdmdmdmdmd/pygatemon#7]
A lot of code in grafana (e.g. the alert plugin) cant handle boolean datatypes correctly. We maybe should use integers (0, 1) therefore.

**Comment by lemoer** [comment]
``` diff
diff --git a/client-influx.py b/client-influx.py
index 69d8cfd..9443076 100644
--- a/client-influx.py
+++ b/client-influx.py
@@ -27,7 +27,8 @@ def create_json(hostname, montype, supernode, value):
             "domain": "default"
         },
         "fields": {
-            "Bool_value": value
+            "Bool_value": value,
+            "Int_value": int(value)
         }
     }
     return json_body
```

**Comment by mdmdmdmdmd** [comment]
pushed your changes in [https://github.com/mdmdmdmdmd/pygatemon/commit/c712903c938234134bad8ba3aaed7e97fc80aab0](url)

**Comment by mdmdmdmdmd** [comment]
should we still report bool values at all?

**Comment by lemoer** [comment]
I think it's okay to push them as well. The amount of storage should be negligible and maybe someday grafana is able to handle booleans in a better way. Then no migration process would be necessary.
